name: Copy Notebooks

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config --global user.name "ponder"
          git config --global user.email "ponder@github.com"
          git config --global credential.helper store 
        env:
          PAT: ${{ secrets.PAT }}

      - name: Copy Notebook files
        run: |
          # Clone the source repository
          git clone https://ponder:${{ secrets.PAT }}@github.com/ponder-org/ponder-notebooks.git

          # Clone the target repository
          git clone https://ponder:${{ secrets.PAT }}@github.com/ponder-org/pandas-web-hub.git
          cd pandas-web-hub

          # Copy the contents of the "ponder notebook" repository to the "pandas web hub" repository
          cp -r ../ponder-notebooks/* ./packages/portal/public/assets/notebook/.

          # Commit and push the changes to the main branch
          git add -A
          git commit -m "auto commit: copy notebooks files"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}